[package]
name = "minidb-engine"
version = "0.1.0"
edition = "2021"
description = "minimalistic database engine"
license = "MIT"

[features]
default = ["storage"]
storage = []
indexing = ["storage"]
persistence = ["storage"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = { version = "*", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1", features = ["derive"] }
